### ISSUE TITLE
Crash with Proguard/R8/minify true

### ISSUE THREAD

**Issue by bernaferrari** [airbnb/MvRx#126]
Both 0.5.0 and 0.6.0 are crashing when minifyEnable true is set, on Android Studio 3.2.1. I downloaded the sample, enabled release, opened it, tapped on an item and BOOOM, crash.

It looks something related to onSaveInstance.

**Comment by Dwite** [comment]
@bernaferrari could you please provide a stack trace of the crash?

**Comment by bernaferrari** [comment]
On sample:

crash 1:
```
2018-11-01 02:13:13.913 26457-26457/com.airbnb.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.sample, PID: 26457
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.airbnb.mvrx.K.b(:114)
        at com.airbnb.mvrx.K.a(:57)
        at com.airbnb.mvrx.J.a(:43)
        at com.airbnb.mvrx.J.a(:16)
        at com.airbnb.mvrx.y.a(:9)
        at android.arch.lifecycle.z.a(:134)
        at com.airbnb.mvrx.K.a(:48)
        at com.airbnb.mvrx.sample.features.dadjoke.B.c(:183)
        at com.airbnb.mvrx.sample.features.dadjoke.B.c(Unknown Source:0)
        at com.airbnb.mvrx.ia.getValue(:49)
        at com.airbnb.mvrx.sample.features.dadjoke.RandomDadJokeFragment.ma(Unknown Source:9)
        at com.airbnb.mvrx.sample.features.dadjoke.RandomDadJokeFragment.ja(:44)
        at com.airbnb.mvrx.sample.core.a.c(:23)
        at com.airbnb.mvrx.sample.core.a.c(:18)
        at e.r.getValue(:74)
        at com.airbnb.mvrx.sample.core.b.la(Unknown Source:7)
        at com.airbnb.mvrx.sample.core.b.c(:27)
        at android.support.v4.app.k.h(:2331)
        at android.support.v4.app.x.a(:1386)
        at android.support.v4.app.x.a(:2617)
        at android.support.v4.app.x.b(:2388)
        at android.support.v4.app.x.c(:2344)
        at android.support.v4.app.x.t(:2245)
        at android.support.v4.app.r.run(:703)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
     Caused by: java.lang.IllegalArgumentException: Unable to create converter for class com.airbnb.mvrx.sample.a.a
        for method a.a
        at i.y$a.a(:755)
        at i.y$a.c(:741)
        at i.y$a.a(:172)
        at i.x.a(:170)
        at i.w.invoke(:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy2.a(Unknown Source)
        at com.airbnb.mvrx.sample.features.dadjoke.RandomDadJokeViewModel.c(:26)
        at com.airbnb.mvrx.sample.features.dadjoke.RandomDadJokeViewModel.<init>(:22)
        at com.airbnb.mvrx.sample.features.dadjoke.RandomDadJokeViewModel$a.a(:36)
        at com.airbnb.mvrx.sample.features.dadjoke.RandomDadJokeViewModel.create(Unknown Source:2)
        	... 32 more
     Caused by: java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
        at e.h.b.a.b.a.b.c(:39)
        at e.h.b.a.b.a.b.c(:36)
        at e.q.getValue(:107)
        at e.h.b.a.b.a.c$a.a(Unknown Source:7)
        at e.h.b.a.b.a.p.b(:172)
        at e.h.b.a.b.a.b.k.<init>(:43)
        at e.h.b.a.b.a.b.k.<init>(:18)
        at e.h.b.a.a.j$a.a(:58)
        at e.h.b.a.fb.a(:58)
        at e.h.b.a.Z.c(:37)
        at e.h.b.a.Z.c(:34)
        at e.h.b.a.gb$a.a(:92)
        at e.h.b.a.gb$c.a(:31)
        at e.h.b.a.Y$b.a(Unknown Source:7)
        at e.h.b.a.I.c(:47)
        at e.h.b.a.I.c(:44)
        at e.h.b.a.gb$a.a(:92)
        at e.h.b.a.gb$c.a(:31)
        at e.h.b.a.T$a.g(Unknown Source:7)
        at e.h.b.a.T.b(:171)
        at e.h.b.a.T.v(:252)
        at c.b.a.b.a.b.a(:184)
        at c.b.a.J.a(:130)
        at i.b.a.a.a(:91)
        at i.x.a(:330)
        at i.x.b(:313)
        at i.y$a.c(:739)
        	... 41 more
```
 
crash 2:

```
2018-11-01 02:14:24.335 28250-28250/com.airbnb.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.sample, PID: 28250
    java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
        at e.h.b.a.b.a.b.c(:39)
        at e.h.b.a.b.a.b.c(:36)
        at e.q.getValue(:107)
        at e.h.b.a.b.a.c$a.a(Unknown Source:7)
        at e.h.b.a.b.a.p.b(:172)
        at e.h.b.a.b.a.b.k.<init>(:43)
        at e.h.b.a.b.a.b.k.<init>(:18)
        at e.h.b.a.a.j$a.a(:58)
        at e.h.b.a.fb.a(:58)
        at e.h.b.a.Z.c(:37)
        at e.h.b.a.Z.c(:34)
        at e.h.b.a.gb$a.a(:92)
        at e.h.b.a.gb$c.a(:31)
        at e.h.b.a.Y$b.a(Unknown Source:7)
        at e.h.b.a.I.c(:47)
        at e.h.b.a.I.c(:44)
        at e.h.b.a.gb$a.a(:92)
        at e.h.b.a.gb$c.a(:31)
        at e.h.b.a.T$a.g(Unknown Source:7)
        at e.h.b.a.T.b(:171)
        at e.h.b.a.T.i(:177)
        at e.h.b.a.G.c(:151)
        at e.h.b.a.G.c(:44)
        at e.h.b.a.gb$a.a(:92)
        at e.h.b.a.gb$c.a(:31)
        at e.h.b.a.T$a.f(Unknown Source:8)
        at e.h.a.d.c(:163)
        at com.airbnb.mvrx.Y.a(:36)
        at com.airbnb.mvrx.Y.a(:34)
        at com.airbnb.mvrx.O.a(:53)
        at com.airbnb.mvrx.O.a(:20)
        at com.airbnb.mvrx.ea.a(:6)
        at com.airbnb.mvrx.M.a(:52)
        at com.airbnb.mvrx.M.a(:43)
        at com.airbnb.mvrx.c.onSaveInstanceState(:39)
        at android.app.Activity.performSaveInstanceState(Activity.java:1555)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1392)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4941)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4229)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4288)
        at android.app.ActivityThread.-wrap25(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

[mapping.txt](https://github.com/airbnb/MvRx/files/2537187/mapping.txt)

**Comment by rossbacher** [comment]
This is odd, I've not seen these crashers before and we are using it in our proguarded app just fine. 

You just built the example app with minify = true? No other modifications?

Let me know what you did and I'll try to repro.

**Comment by bernaferrari** [comment]
Yeah. If you open the random dad joke, it crashes, and if you press home
button (which triggers on save instance) it also crashes.

**Comment by rossbacher** [comment]
I think I know what might be going on here. 

You cannot just set `minify = true` you have to have a default config for the main app like:

```
android {
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
    ...
}```


See: https://developer.android.com/studio/build/shrink-code

We do provide a consumer proguard file for the lib but as the demo app is not intended to be obfuscated we did not add that and I don't think there is any use in adding that.

**Comment by bernaferrari** [comment]
Did it work on the sample app? When I tested I did both on debug and
release (which already has the rules) and got the crash.

**Comment by rossbacher** [comment]
i did not have time to test it yet. But if there is a problem it is just for the test app. The lib itself is fine as we use it in prod with proguard.

**Comment by bernaferrari** [comment]
This is weird, I got this crash on my app (
https://github.com/bernaferrari/SDKMonitor/blob/master/app/build.gradle),
then I went to the sample and got the same issue.

**Comment by SocialSupaCrew** [comment]
Hello, I also have a crash when building my app with proguard and it also seems related to the `onSaveInstanceState`
Here is the stack trace of the fatal exception : 
```
Fatal Exception: java.lang.ExceptionInInitializerError
       at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader.(Unknown Source)
       at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:148)
       at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.(JvmBuiltIns.kt:56)
       at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.(JvmBuiltIns.kt:31)
       at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:54)
       at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:32)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(Unknown Source:7)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:46)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:43)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(Unknown Source:7)
       at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:172)
       at kotlin.reflect.jvm.internal.KClassImpl.getMemberScope$kotlin_reflection(KClassImpl.kt:178)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:152)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:43)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(Unknown Source:8)
       at kotlin.reflect.full.KClasses.getDeclaredMemberProperties(KClasses.kt:163)
       at com.airbnb.mvrx.PersistStateKt.persistState(PersistState.kt:36)
       at com.airbnb.mvrx.PersistStateKt.persistState$default(PersistState.kt:34)
       at com.airbnb.mvrx.MvRxViewModelStore$saveViewModels$3$1.invoke(MvRxViewModelStore.kt:53)
       at com.airbnb.mvrx.MvRxViewModelStore$saveViewModels$3$1.invoke(MvRxViewModelStore.kt:20)
       at com.airbnb.mvrx.StateContainerKt.withState(StateContainer.kt:6)
       at com.airbnb.mvrx.MvRxViewModelStore.saveViewModels(MvRxViewModelStore.kt:52)
       at com.airbnb.mvrx.MvRxViewModelStore.saveViewModels(MvRxViewModelStore.kt:43)
       at com.airbnb.mvrx.BaseMvRxFragment.onSaveInstanceState(BaseMvRxFragment.kt:22)
       at com.MY_APP.common.mvrx.BaseFragment.onSaveInstanceState(MvRxBaseFragment.kt:54)
       at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2626)
       at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2910)
       at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2971)
       at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:591)
       at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:510)
       at android.app.Activity.performSaveInstanceState(Activity.java:1555)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1392)
       at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4943)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4231)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4290)
       at android.app.ActivityThread.-wrap25(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Here is how I use the proguard file : 
```
android {
    buildTypes {
            release {
                minifyEnabled true
                shrinkResources true
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
}
```

**Comment by bearprada** [comment]
is it solve the problem? I get the same crash when enable proguard setting on the sample app

**Comment by rossbacher** [comment]
Hey @bearprada yes, this should solve the problem, but this configuration is specific to this demo app, for your own app it might be different. I'll merge this as soon as it gets approved.

**Comment by lwj1994** [comment]
the minifyEnabled is false。
why do I have the same problem?  @rossbacher 

```
java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
	at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:39)
	at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:36)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion.getInstance(Unknown Source:7)
	at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:127)
	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:43)
	at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:18)
	at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:58)
	at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:37)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:34)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(Unknown Source:7)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(Unknown Source:7)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:179)
	at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:196)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:91)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(Unknown Source:7)
	at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:235)
	at kotlin.reflect.full.KClasses.getPrimaryConstructor(KClasses.kt:40)
	at com.airbnb.mvrx.PersistStateKt.persistState(PersistState.kt:38)
	at com.airbnb.mvrx.PersistStateKt.persistState$default(PersistState.kt:34)
	at com.airbnb.mvrx.MvRxViewModelStore$saveViewModels$3$1.invoke(MvRxViewModelStore.kt:54)
	at com.airbnb.mvrx.MvRxViewModelStore$saveViewModels$3$1.invoke(MvRxViewModelStore.kt:21)
	at com.airbnb.mvrx.StateContainerKt.withState(StateContainer.kt:6)
	at com.airbnb.mvrx.MvRxViewModelStore.saveViewModels(MvRxViewModelStore.kt:53)
	at com.airbnb.mvrx.MvRxViewModelStore.saveViewModels(MvRxViewModelStore.kt:44)
	at com.airbnb.mvrx.BaseMvRxFragment.onSaveInstanceState(BaseMvRxFragment.kt:22)
	at com.xiachufang.lanfan.common.core.BaseFragment.onSaveInstanceState(BaseFragment.kt:72)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2626)
	at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2910)
	at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2971)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2628)
	at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2910)
	at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2971)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2628)
	at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2910)
	at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2971)
	at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:134)
	at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:591)
	at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:510)
	at com.airbnb.mvrx.BaseMvRxActivity.onSaveInstanceState(BaseMvRxActivity.kt:38)
	at android.app.Activity.performSaveInstanceState(Activity.java:1555)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1392)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4941)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4229)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4288)
	at android.app.ActivityThread.-wrap25(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

**Comment by bernaferrari** [comment]
If I remember well, a newer version of Android Studio enable some kind of shrinking with r8/d8 even when minify is false, probably related to app bundle. Are you using app bundle? I don't remember the scenario and didn't find where I read it, but might be worth checking it (or disabling r8 powers).
