### ISSUE TITLE
Crashed when automatically initializing State using Fragment's arguments

### ISSUE THREAD

**Issue by talenguyen** [airbnb/MvRx#143]
When using MvRx I get this error:

~~~java

java.lang.IllegalStateException: Attempt to auto create the MvRx state class DemoState has failed. It must have default values for every property or a secondary constructor for Arg. 

	at com.airbnb.mvrx.MvRxExtensionsKt._initialStateProvider(MvRxExtensions.kt:132)
	at com.airbnb.mvrx.MvRxExtensionsTest.testInitialStateProvider(MvRxExtensionsTest.kt:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
~~~

After reading the code of the function: `MvRxExtensionsKt._initialStateProvider(MvRxExtensions.kt:132)` then I found out that this condition incorrectly `isAssignableTo(constructor.parameterTypes[0], argType)`. Because when checked `isAssignableTo(Parcelable::class.java, MyArgs::class.java)` where `MyArgs` implement `Parcelable` the result is `false`. So, I think it should be: `constructor.parameterTypes.size == 1 && isAssignableTo(argType, constructor.parameterTypes[0])`. I added this test case to demonstrate:

~~~kotlin
class MvRxExtensionsTest {

  @Parcelize
  data class Arg(val value: String) : Parcelable

  class DemoState(val arg: Parcelable) : MvRxState

  @Test
  fun testInitialStateProvider() {
    val state = _initialStateProvider(DemoState::class.java, Arg("Hello"))
    assertEquals("Hello", (state.arg as Arg).value)
  }
}
~~~

**Comment by ducgao** [comment]
That's awesome, I had tried to apply fix and now it's work perfectly.

**Comment by elihart** [comment]
Thanks for this, merged!
