### ISSUE TITLE
Proguard obfuscate MvRxViewModelFactory method

### ISSUE THREAD

**Issue by lirik16** [airbnb/MvRx#176]
In the version [0.7.0](https://github.com/airbnb/MvRx/tree/v0.7.0), the class [MvRxViewModelProvider](https://github.com/airbnb/MvRx/blob/v0.7.0/mvrx/src/main/kotlin/com/airbnb/mvrx/MvRxViewModelProvider.kt) was changed. It uses reflection for [getting initialState method of the companion object](https://github.com/airbnb/MvRx/blob/v0.7.0/mvrx/src/main/kotlin/com/airbnb/mvrx/MvRxViewModelProvider.kt#L92). The app will crash If you enable Proguard because it'll not find `initialState` method of the companion object.
`Caused by: java.lang.NoSuchMethodException: initialState [class com.airbnb.mvrx.ViewModelContext]
        at java.lang.Class.getMethod(Class.java:624)
        at java.lang.Class.getMethod(Class.java:603)
        at com.airbnb.mvrx.MvRxViewModelProvider.createInitialState(MvRxViewModelProvider.kt:96)
        at com.airbnb.mvrx.MvRxViewModelProvider.createViewModel$mvrx_release(MvRxViewModelProvider.kt:47)
        at com.airbnb.mvrx.MvRxViewModelProvider.createViewModel$mvrx_release$default(MvRxViewModelProvider.kt:45)
        at com.airbnb.mvrx.MvRxViewModelProvider$get$factory$1.invoke(MvRxViewModelProvider.kt:33)
        at com.airbnb.mvrx.MvRxViewModelProvider$get$factory$1.invoke(MvRxViewModelProvider.kt:14)
        at com.airbnb.mvrx.MvRxFactory.create(MvRxFactory.kt:9)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:135)
        at com.airbnb.mvrx.MvRxViewModelProvider.get(MvRxViewModelProvider.kt:37)`

I suggest the following:
- Add corresponding rules to the library Proguard configuration, something like this `-keep class * implements com.airbnb.mvrx.MvRxViewModelFactory { *; }`
- Add building of release version of the samples with enabled Proguard and [execute it with an emulator](https://docs.travis-ci.com/user/languages/android/#how-to-create-and-start-an-emulator) for release versions of the library by CI server. I think it should help with preventing that kind of error in the future. 
I'll create a pull request for the changes if have time this week.

Also, thank you for the good library, I really enjoy to use it :)

**Comment by jonasbark** [comment]
Sorry to hijack this issue but we've got a crash related to Proguard as well with 0.7.0:

```
kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader: Provider kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl not found
...
com.airbnb.mvrx.PersistStateKt.persistState (PersistState.kt:36)
--
  | com.airbnb.mvrx.PersistStateKt.persistState$default (PersistState.kt:34)
  | com.airbnb.mvrx.MvRxViewModelStore$saveViewModels$3$1.invoke (MvRxViewModelStore.kt:53)
```

We fixed it by including
```
-keep interface kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader
-keep class kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl
```
