### ISSUE TITLE
Companion objects of MvRxViewModel must now implement MvRxViewModelFactory where previously they didn't

### ISSUE THREAD

**Issue by okarm** [airbnb/MvRx#189]
Prior to 0.7.0 it was not necessary for `MvRxViewModel`'s companion object to implement `MvRxViewModelFactory` when there was no need for it. 

After the change whenever the `MvRxViewModel` has a companion object the companion object *must* implement `MvRxViewModelFactory` otherwise it will crash with 
```
     Caused by: java.lang.NoSuchMethodException: initialState [class com.airbnb.mvrx.ViewModelContext]
        at java.lang.Class.getMethod(Class.java:624)
        at java.lang.Class.getMethod(Class.java:603)
        at com.airbnb.mvrx.MvRxViewModelProvider.createInitialState(MvRxViewModelProvider.kt:96)
        at com.airbnb.mvrx.MvRxViewModelProvider.createViewModel$mvrx_release(MvRxViewModelProvider.kt:47)
        at com.airbnb.mvrx.MvRxViewModelProvider.createViewModel$mvrx_release$default(MvRxViewModelProvider.kt:45)
        at com.airbnb.mvrx.MvRxViewModelProvider$get$factory$1.invoke(MvRxViewModelProvider.kt:33)
        at com.airbnb.mvrx.MvRxViewModelProvider$get$factory$1.invoke(MvRxViewModelProvider.kt:14)
        at com.airbnb.mvrx.MvRxFactory.create(MvRxFactory.kt:9)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:135)
        at com.airbnb.mvrx.MvRxViewModelProvider.get(MvRxViewModelProvider.kt:37)
        at AccountContainerFragment$$special$$inlined$fragmentViewModel$3.invoke(MvRxExtensions.kt:131)
        at AccountContainerFragment$$special$$inlined$fragmentViewModel$3.invoke(MvRxExtensions.kt)
        at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:49)
        at com.airbnb.mvrx.lifecycleAwareLazy$1.onStart(lifecycleAwareLazy.kt:28)
        at java.lang.reflect.Method.invoke(Native Method)
```

I suggest this change be included in the changelog and the documentation.

**Comment by gpeal** [comment]
@BenSchwab FYI

**Comment by BenSchwab** [comment]
Hmm, good catch! This should be fixable.
