### ISSUE TITLE
Kotlin Reflect FieldOverridabilityCondition

### ISSUE THREAD

**Issue by marukami** [airbnb/MvRx#232]
When the app is been restored from process death I'm always getting the reflection error below. Not sure if related to error @gpeal reported #231 

TL;DR error
```
 at kotlin.reflect.full.KClasses.getDeclaredMemberProperties(SourceFile:163)
 at com.airbnb.mvrx.BaseMvRxViewModel$1.call(SourceFile:48)
 at com.airbnb.mvrx.BaseMvRxViewModel$1.call(SourceFile:28)
```

Full error 
```
 Undeliverable exceptions
 io.reactivex.exceptions.OnErrorNotImplementedException: kotlin.reflect.jvm.internal.impl.resolve.ExternalOverridabilityCondition: Provider kotlin.reflect.jvm.internal.impl.load.java.FieldOverridabilityCondition not found
     at io.reactivex.internal.observers.EmptyCompletableObserver.onError(SourceFile:51)
     at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(SourceFile:74)
     at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(SourceFile:39)
     at io.reactivex.Completable.subscribe(SourceFile:2171)
: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
     at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(SourceFile:64)
     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:38)
     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:26)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     at java.lang.Thread.run(Thread.java:764)
 Caused by: java.util.ServiceConfigurationError: kotlin.reflect.jvm.internal.impl.resolve.ExternalOverridabilityCondition: Provider kotlin.reflect.jvm.internal.impl.load.java.FieldOverridabilityCondition not found
     at java.util.ServiceLoader.fail(ServiceLoader.java:233)
     at java.util.ServiceLoader.-wrap1(Unknown Source:0)
     at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:373)
     at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:416)
     at java.util.ServiceLoader$1.next(ServiceLoader.java:494)
     at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(SourceFile:1153)
     at kotlin.collections.CollectionsKt.toCollection(Unknown Source:0)
     at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(SourceFile:1186)
     at kotlin.collections.CollectionsKt.toMutableList(Unknown Source:0)
     at kotlin.collections.CollectionsKt___CollectionsKt.toList(SourceFile:1177)
     at kotlin.collections.CollectionsKt.toList(Unknown Source:0)
     at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.<clinit>(SourceFile:46)
     at kotlin.reflect.jvm.internal.impl.resolve.OverridingUtil.generateOverridesInFunctionGroup(Unknown Source:0)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.generateFakeOverrides(SourceFile:255)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.computeNonDeclaredProperties(SourceFile:246)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeProperties(SourceFile:148)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.access$computeProperties(SourceFile:40)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$properties$1.invoke(SourceFile:68)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope$properties$1.invoke(SourceFile:40)
     at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(SourceFile:440)
     at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(SourceFile:515)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.getContributedVariables(SourceFile:165)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedVariables(SourceFile:224)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.addFunctionsAndProperties(SourceFile:213)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedMemberScope.computeDescriptors(SourceFile:181)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(SourceFile:210)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope$allDescriptors$1.invoke(SourceFile:203)
     at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(SourceFile:346)
     at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(SourceFile:402)
     at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedClassDescriptor$DeserializedClassMemberScope.getContributedDescriptors(SourceFile:215)
     at kotlin.reflect.jvm.internal.impl.resolve.scopes.ResolutionScope$DefaultImpls.getContributedDescriptors$default(SourceFile:52)
     at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getMembers(SourceFile:64)
     at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(SourceFile:159)
     at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(SourceFile:44)
     at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:92)
     at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:31)
     at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(Unknown Source:8)
     at kotlin.reflect.full.KClasses.getDeclaredMemberProperties(SourceFile:163)
     at com.airbnb.mvrx.BaseMvRxViewModel$1.call(SourceFile:48)
     at com.airbnb.mvrx.BaseMvRxViewModel$1.call(SourceFile:28)
     at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(SourceFile:35)
 	... 9 more
 Caused by: java.lang.ClassNotFoundException: kotlin.reflect.jvm.internal.impl.load.java.FieldOverridabilityCondition
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:453)
     at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:371)
 	... 47 more
 Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.jvm.internal.impl.load.java.FieldOverridabilityCondition" 
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 	... 50 more
```

**Comment by gpeal** [comment]
@marukami @rossbacher could this be related to proguard? It looks similar to [this](https://github.com/square/moshi/issues/402) issue.

**Comment by kalyandechiraju** [comment]
This is due to proguard. Even with suggested rules (from wiki), same exception comes in release builds. Debug builds are fine.

**Comment by rossbacher** [comment]
@marukami did you try adding the kotlin reflect settings from the sample app? Like https://github.com/airbnb/MvRx/blob/master/sample/proguard-project.pro#L15-L20 @kalyandechiraju sounds like you have added that, can you try adding? 
```
-keep class kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl
```
We have that in our sample app and also in the Airbnb app for use with Kotlin reflection. Let me know if it works, if it does I'll update the documentation and also update our sample config file to be a bit clearer.

**Comment by marukami** [comment]
@rossbacher Almost I have 

```
-keep public class kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.* { public *; }
```

**Comment by rossbacher** [comment]
@marukami Can you try what I posted? Can you repo the same error with the sample app?

**Comment by marukami** [comment]
> @marukami Can you try what I posted? 

@rossbacher Sure, no worries.

> Can you repo the same error with the sample app?

I'll give it a go and see if I can trigger it.

**Comment by gpeal** [comment]
@marukami can this be closed?

**Comment by marukami** [comment]
@gpeal Yes, I've not seen the error pop up again with either rule.
