### ISSUE TITLE
Crash after opening proguard

### ISSUE THREAD

**Issue by wdeo3601** [airbnb/MvRx#251]
When my activity/fragment is restored by the system and  `mvrxViewModelStore.restoreViewModels(this, savedInstanceState)` invoke，i get this error:  

```
UncaughtException detected: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wln100.future/com.wln100.exam.league.view.home.LeagueActivity}: java.lang.IllegalStateException: c has no primary constructor!
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3108)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.IllegalStateException: c has no primary constructor!
        at com.airbnb.mvrx.oa.a(PersistState.kt:45)
        at com.airbnb.mvrx.ea.a(MvRxViewModelStore.kt:2)
        at com.airbnb.mvrx.ea.a(MvRxViewModelStore.kt:1)
        at com.airbnb.mvrx.pa.a(MvRxStateFactory.kt:2)
        at com.airbnb.mvrx.Y.a(MvRxViewModelProvider.kt:10)
        at com.airbnb.mvrx.Y.a(MvRxViewModelProvider.kt:9)
        at com.airbnb.mvrx.ba.a(MvRxViewModelStore.kt:41)
        at com.airbnb.mvrx.ba.a(MvRxViewModelStore.kt:33)
        at com.airbnb.mvrx.ba.a(MvRxViewModelStore.kt:23)
        at com.airbnb.mvrx.ba.a(MvRxViewModelStore.kt:21)
        at com.wln100.base.view.j.onCreate(BaseMvRxFragment.kt:1)
        at com.wln100.base.view.e.onCreate(BaseFragment.kt:1)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:5)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:47)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:6)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:150)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:2)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3)
        at androidx.fragment.app.j.b(FragmentController.java:1)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:20)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:8)
        at me.yokeyword.fragmentation.SupportActivity.onCreate(SupportActivity.java:1)
        at com.wln100.base.view.BaseMvRxActivity.onCreate(BaseMvRxActivity.kt:2)
        at com.wln100.base.view.BaseActivity.onCreate(BaseActivity.kt:1)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214)   
```  

my `proguard-rules` is:  
```
  # mvrx
-keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl
-keep class kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl
-keep class kotlin.reflect.jvm.internal.impl.load.java.FieldOverridabilityCondition
-keep class kotlin.reflect.jvm.internal.impl.load.java.ErasedOverridabilityCondition
-keep class kotlin.reflect.jvm.internal.impl.load.java.JavaIncompatibilityRulesOverridabilityCondition
-if class **$Companion extends **
-keep class <2>
-if class **$Companion implements **
-keep class <2>
-keep class kotlin.Metadata { *; }
-dontwarn kotlin.**
-keepclassmembers class ** extends com.airbnb.mvrx.BaseMvRxViewModel {
    ** Companion;
}
-keepclassmembers class ** extends com.airbnb.mvrx.BaseMvRxViewModel {
    public <init>(...);
    public static *** create(...);
    public static *** initialState(...);
}
-keepclassmembers class ** implements com.airbnb.mvrx.MvRxViewModelFactory {
     public <init>(...);
     public *** create(...);
     public *** initialState(...);
}
-keepnames class * implements com.airbnb.mvrx.MvRxViewModelFactory
-keepclassmembers class ** implements com.airbnb.mvrx.MvRxState {
   *;
}
```   

Using Mvrx Version: `api 'com.airbnb.android:mvrx:1.0.2'`

is my `proguard-rules` wrong?

**Comment by wdeo3601** [comment]
MvRxState is encapsulated in my project：   
```
interface InitialState : MvRxState {
    val repoAsync: Async<Any>
    val initAsync: Async<Any>
}
```  
so, the proguard-rules `-keepclassmembers class ** implements com.airbnb.mvrx.MvRxState {*;}` doesn't work in my project.  

finally, i add this proguard-rules solved my problem:  
```
-keep class com.airbnb.mvrx.MvRxState
-keep class com.airbnb.mvrx.Async
-keep class com.wln100.base.view.InitialState
-keep class ** implements com.wln100.base.view.InitialState
```
