### ISSUE TITLE
ClassNotFoundException on 1.0.2

### ISSUE THREAD

**Issue by dlleixap** [airbnb/MvRx#253]
Hi there,

We have recently updated mvrx dependency from `1.0.1` to `1.0.2`. Which has messed up lots of our classes on our release builds with proguard. We are basically getting `java.lang.ClassNotFoundException` all over the app(data classes, enums, Async from mvrx, etc..) 

Reverting to 1.0.1 fixes the problem

**Comment by gpeal** [comment]
@dlleixap Hmm, could you create a sample project that reproduces this? We had one other report of an R8 issue but a repro would be helpful!

**Comment by tasomaniac** [comment]
So, I've enabled `R8` for the `todomvrx` module and build the release APK and cannot reproduce this issue there. The app works as expected.

For the curious, here is a branch where I have it setup: https://github.com/tasomaniac/MvRx/tree/todomvrx-with-r8

**Comment by digitalbuddha** [comment]
Here's the crash
```Caused by java.lang.ClassNotFoundException: Didn't find class "app.tivi.data.entities.SearchResults" on path: DexPathList[[zip file "/data/app/app.tivi-hejDv5FPePXFslYsWE_rCw==/base.apk", zip file "/data/app/app.tivi-hejDv5FPePXFslYsWE_rCw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/app.tivi-hejDv5FPePXFslYsWE_rCw==/lib/arm64, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass + 134(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass + 379(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass + 312(ClassLoader.java:312)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getFunctions(KDeclarationContainerImpl.java:59)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.parseType + 277(KDeclarationContainerImpl.java:277)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getProperties(KDeclarationContainerImpl.java:1)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.loadReturnType + 292(KDeclarationContainerImpl.java:292)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.getFunctions(KDeclarationContainerImpl.java:33)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findMethodBySignature + 223(KDeclarationContainerImpl.java:223)
       at kotlin.reflect.jvm.internal.ReflectProperties.$$$reportNull$$$0(ReflectProperties.java:1418)
       at com.google.android.material.math.MathUtils.lerp(MathUtils.java:1418)
       at com.google.android.gms.internal.measurement.zzia.zzg(zzia.java:1418)
       at kotlin.reflect.jvm.internal.KPropertyImplKt.computeCallerForAccessor + 223(KPropertyImplKt.java:223)
       at kotlin.reflect.jvm.internal.KPropertyImplKt.access$computeCallerForAccessor + 1(KPropertyImplKt.java:1)
       at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke + 156(KPropertyImpl.java:156)
       at kotlin.reflect.jvm.internal.KPropertyImpl$Getter$caller$2.invoke + 147(KPropertyImpl.java:147)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke + 62(ReflectProperties.java:62)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue + 31(ReflectProperties.java:31)
       at kotlin.reflect.jvm.internal.KPropertyImpl$Getter.getCaller(KPropertyImpl.java:1)
       at kotlin.reflect.jvm.internal.KCallableImpl.call + 106(KCallableImpl.java:106)
       at kotlin.reflect.jvm.internal.KProperty1Impl.get + 35(KProperty1Impl.java:35)
       at com.airbnb.mvrx.BaseMvRxViewModel.warmReflectionCache + 74(BaseMvRxViewModel.java:74)
       at com.airbnb.mvrx.BaseMvRxViewModel$1.call + 48(BaseMvRxViewModel.java:48)
       at com.airbnb.mvrx.BaseMvRxViewModel$1.call + 31(BaseMvRxViewModel.java:31)
       at -$$LambdaGroup$js$vONjP0J2wUvJupZ08yCPiXH_-10.call(-.java:4)
       at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual + 36(CompletableFromCallable.java:36)
       at io.reactivex.Completable.subscribe + 2309(Completable.java:2309)
       at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run + 64(CompletableSubscribeOn.java:64)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call + 38(ScheduledDirectTask.java:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call + 26(ScheduledDirectTask.java:26)
       at java.util.concurrent.FutureTask.run + 266(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run + 301(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)
```

It's coming from https://github.com/airbnb/MvRx/blob/4bf5e11aa0aae22c67fb9b7651549fe5340c5f64/mvrx/src/main/kotlin/com/airbnb/mvrx/BaseMvRxViewModel.kt#L68  which calls `(prop as? KProperty1<S, Any?>)?.get(initialState)`  I think kotlin reflect and r8 don't play nice together

**Comment by gpeal** [comment]
@digitalbuddha @tasomaniac @BenSchwab @chrisbanes @dlleixap For now, we could wrap this block in a try/catch with a completion flag that is set at the end of the block. I would like to try this and ensure that it only fails at startup and will succeed on a subsequent call though.

**Comment by digitalbuddha** [comment]
I don't think it will. The problem does not seem transient but more kotlin reflect accessing a class by a name that does not exist after r8 is run

**Comment by tasomaniac** [comment]
Why do you think it does not happen with the sample?

**Comment by mt-mitchell** [comment]
Does this happen when the R8 full mode is enabled (`android.enableR8.fullMode=true`) or even in with default `compatible` mode?

**Comment by chrisbanes** [comment]
Happens on the the default compat mode for me

**Comment by tasomaniac** [comment]
Also for me. I believe it would also happen with Proguard. It's because of obfuscation. Class names change during that process.

**Comment by rossbacher** [comment]
I cannot repro this yet, but if someone would be able to provide a stacktrace, and an apk with r8 shrinking applied and one without that would help me greatly to get to the bottom of this. A repo project would still be the best option.

**Comment by chrisbanes** [comment]
Repo project: https://github.com/chrisbanes/tivi
Update the dependency to 1.0.2 in `buildSrc../`, and then `./gradlew app:assembleRelease`

**Comment by rossbacher** [comment]
I was able to find the reason for the `ClassNotFoundException`. It is basically Progurad/Dexguard/R8 s missing support for Kotlin reflection. It's caused by the way 1.0.2 handles reflection caching. Basically the type is now also handled via reflection in objects implementing `MvRxState`. 

@gpeal is that something we could avoid? I'm also doing some research on how to keep the types as is for objects that are used in `MvRxState` objects.

It is not reproducible in the sample app as the state consists either of simple data types or JSON model objects. The type of those is kept by a different keep rule.

**Comment by gpeal** [comment]
@rossbacher We could experiment with doing other forms of kotlin reflect initialization. The goal is to remove kotlin reflect init from being in the hot path of onSaveInstanceState. Calling some other kotlin reflect functions may be sufficient, we would just want to benchmark it.

**Comment by tasomaniac** [comment]
Hmm, so `warmReflectionCache` is actually only needed for properties with `PersistState` annotation then?

If you warm the reflection **only** for the fields with that annotation, then it would be just that the users will need to `keep` those classes with `PersistState` annotation. This will remove majority of the problem and the rest will be easy to handle by the users.

**Comment by rossbacher** [comment]
I'll have another look at this tomorrow, I have a rule that should work but is also obviously more generic. 

@gpeal if we could avoid using reflection on the type this should go away, no idea how to do that.

@tasomaniac I'll look a bit into this tomorrow if I have time. But making progress.

**Comment by tasomaniac** [comment]
Please have a look at #264 for my trial at it.

**Comment by gpeal** [comment]
@rossbacher You can experiment with using different Kotlin reflect init. It may not need to be so specific on the type. To test it, create a state class with ~100 `@PeristState` annotations and benchmark how long it takes to persist it.

**Comment by rossbacher** [comment]
I have a Proguard rule that should work (but does not in R8, testing with Proguard (but first need to find out how to use Proguard in AGP 3.5). If anyone who can repro this is using Proguard, can you try adding this to your rules?

@gpeal No idea of how this would work, I think because it is using `KProperty` the type is read through reflection too.

**Comment by tasomaniac** [comment]
Can you share  the rule? I put some thought into this but couldn't figure out how to keep these in a smart way with Proguard.

**Comment by rossbacher** [comment]
Sure: 

```
-keepclassmembers,includedescriptorclasses class * implements com.airbnb.mvrx.MvRxState {
    public <fields>;
 }
```

it does not work though. :-) I don't know about the Lists but at least the objects should be kept by this. I also had:

```
-if class * implements com.airbnb.mvrx.MvRxState {
                public *** *;
             }
-keep class <2>
```

which also does not work. :-(

**Comment by rossbacher** [comment]
Actually I think I found the mistake... 🤦‍♂

**Comment by rossbacher** [comment]
Ok, I put the fix up, this worked fine on @chrisbanes Tivi project, while adding repo steps to the sample project I found some weirdness that needs some work before I can do so. But no need to wait with this for that.

**Comment by rossbacher** [comment]
I closed my previous PR in favor of a bit broader one (https://github.com/airbnb/MvRx/pull/267). This also adds a repo case to the sample app and adjusts some shrinking settings to make more sense. 

On top of that the new rules shrink the sample up a few % points better.
