### ISSUE TITLE
Proguard-related crash on Fragment recreation

### ISSUE THREAD

**Issue by aderington** [airbnb/MvRx#299]
Reproduced with MvRx v1.1.0 and the TodoMvRx sample app.

#### Steps to Reproduce
1. Developer Options -> Don't Keep Activities
2. Launch minified "TodoMvRx" sample app _(note that debugMode in the viewmodel must be false)_
3. Navigate away from TodoMvRx app in recent apps list
4. Return to TodoMvRx app from the recent apps list

#### To Fix the Crash
Add the following line to `proguard-rules.pro`
`
-keep class kotlin.Metadata { *; }
`

#### Crash Log
`
2019-10-02 15:20:35.934 26866-26866/com.airbnb.mvrx.todoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.mvrx.todoapp, PID: 26866
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.airbnb.mvrx.todoapp/com.airbnb.mvrx.todomvrx.MainActivity}: java.lang.IllegalStateException: TasksState has no primary constructor!
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: TasksState has no primary constructor!
        at com.airbnb.mvrx.PersistStateKt.a(PersistState.kt:97)
        at com.airbnb.mvrx.MvRxViewModelStore$restoreViewModel$1.a(MvRxViewModelStore.kt:124)
        at com.airbnb.mvrx.MvRxViewModelStore$restoreViewModel$1.a(MvRxViewModelStore.kt:20)
        at com.airbnb.mvrx.RealMvRxStateFactory.a(MvRxStateFactory.kt:27)
        at com.airbnb.mvrx.MvRxViewModelProvider.a(MvRxViewModelProvider.kt:49)
        at com.airbnb.mvrx.MvRxViewModelProvider.a(MvRxViewModelProvider.kt:47)
        at com.airbnb.mvrx.MvRxViewModelStore.a(MvRxViewModelStore.kt:124)
        at com.airbnb.mvrx.MvRxViewModelStore.a(MvRxViewModelStore.kt:109)
        at com.airbnb.mvrx.MvRxViewModelStore.a(MvRxViewModelStore.kt:84)
        at com.airbnb.mvrx.MvRxViewModelStore.a(MvRxViewModelStore.kt:74)
        at com.airbnb.mvrx.BaseMvRxActivity.onCreate(BaseMvRxActivity.kt:33)
        at com.airbnb.mvrx.todomvrx.MainActivity.onCreate(MainActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
`

**Comment by rossbacher** [comment]
The `proguard-rules.pro` rules file inside the `mvrx` lib purposefully only contains rules that are specific to MvRx, it does not contain rules that are required to enable general features (like Kotlin reflection) even though they might be used by the lib. We expect the these things to be configured on the app level.

We are actually doing this with the sample app but it was forgotten to add it to the new `todomvrx` sample app. 

In the future I even want to separate the rules that are required because of missing `@Metadata` annotation support in Proguard/Dexguard/R8 from from the actual lib rules, as some of these tools will gain `@Metadata` processing support and thus some of those rules are not required anymore with that in place.

I'm going to replace your PR with a fix to how we handle the rules to the sample apps in a bit.

**Comment by rossbacher** [comment]
I created #304 to fix this issue.

**Comment by aderington** [comment]
Thanks!  It was unexpected to crash in this way in production and is not a common flow that we test.
