### ISSUE TITLE
add 'jvmTarget = "1.8", app crash

### ISSUE THREAD

**Issue by yjbGitHub** [airbnb/MvRx#323]
Hi guys,
I add  the  `kotlinOptions{
        jvmTarget = "1.8"
    }` in app build.gradle .

then app crash
` io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoSuchMethodError: No static method hashCode(I)I in class Ljava/lang/Integer; or its super classes (declaration of 'java.lang.Integer' appears in /system/framework/core-libart.jar)
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoSuchMethodError: No static method hashCode(I)I in class Ljava/lang/Integer; or its super classes (declaration of 'java.lang.Integer' appears in /system/framework/core-libart.jar)
        at com.puppy.aispell.data.entity.CookingSceneWordsEntity.hashCode(CookingSceneWordsEntity.kt)
        at java.util.ArrayList.hashCode(ArrayList.java:603)
        at com.airbnb.mvrx.Success.hashCode(Async.kt)
        at com.puppy.aispell.viewmodels.MainActState.hashCode(MainViewModel.kt)
        at com.airbnb.mvrx.MutableStateChecker$StateWrapper.hashCode(MvRxMutabilityHelper.kt)
        at com.airbnb.mvrx.MutableStateChecker$StateWrapper.<init>(MvRxMutabilityHelper.kt:61)
        at com.airbnb.mvrx.MutableStateChecker.onStateChanged(MvRxMutabilityHelper.kt:77)
        at com.airbnb.mvrx.BaseMvRxViewModel$setState$1.invoke(BaseMvRxViewModel.kt:145)
        at com.airbnb.mvrx.BaseMvRxViewModel$setState$1.invoke(BaseMvRxViewModel.kt:33)
        at com.airbnb.mvrx.RealMvRxStateStore.flushSetStateQueue(RealMvRxStateStore.kt:190)
        at com.airbnb.mvrx.RealMvRxStateStore.flushQueues(RealMvRxStateStore.kt:181)
        at com.airbnb.mvrx.RealMvRxStateStore.access$flushQueues(RealMvRxStateStore.kt:18)
        at com.airbnb.mvrx.RealMvRxStateStore$1.accept(RealMvRxStateStore.kt:52)
        at com.airbnb.mvrx.RealMvRxStateStore$1.accept(RealMvRxStateStore.kt:18)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) `

**Comment by gpeal** [comment]
This seems to be working fine so there may be something else wrong with your app.
