### ISSUE TITLE
by parentFragmentViewModel Not working as intended

### ISSUE THREAD

**Issue by emitchel** [airbnb/MvRx#348]
![image](https://user-images.githubusercontent.com/3791583/74356655-4eb92600-4d84-11ea-8608-7905c9ad7577.png)

[Comparing 2.0.0-alpha2 to 1.3 stable](https://github.com/airbnb/MvRx/compare/1.3.0...2.0.0-alpha2#diff-a6f85ba829490bbb2abb34e827a06da8R76)

We are using the alpha channel (2.0.0-alpha2)  to take advantage of viewModelConfigFactory, and we're attempting to use a parent fragment viewodel in a nested fragment. 

It's failing because it attempts to use the parent of the parent to find the viewModel.

Using `by parentFragmentViewModel()` on alpha first attempts to find the viewmodel against the fragment calling it (ChildFragment) instead of the parent. Then it erroneously attempts to traverse up the parent tree, starting with parent's parent.

At first, I thought it was due to the child fragment being instantiated via xml and maybe the parent fragment hasn't instantiated yet, but stepping through you can see the parent fragment has the view model instantiated by the time the child fragment is attempting to fetch it. 

Other delegate providers `by existingViewModel` or `by activityViewModel` don't work because it seems the parent fragment view model isn't scoped to the overarching activity - NOTE: we are using the navigation library with one activity. 

Stacktrace 

    2020-02-12 10:54:43.083 25064-25064/fdsa.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fdsa.debug, PID: 25064
    java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
   (more here)

     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.airbnb.mvrx.MvRxFactoryKt.createViewModel(MvRxFactory.kt:50)
        at com.airbnb.mvrx.MvRxFactoryKt.access$createViewModel(MvRxFactory.kt:1)
        at com.airbnb.mvrx.MvRxFactory.create(MvRxFactory.kt:27)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at com.airbnb.mvrx.MvRxViewModelProvider.get(MvRxViewModelProvider.kt:63)
        at com.airbnb.mvrx.MvRxViewModelProvider.get$default(MvRxViewModelProvider.kt:38)
        at fdsa.ChildFragment$$special$$inlined$parentFragmentViewModel$1.invoke(MvRxExtensions.kt:97)
        at fdas.ChildFragment$$special$$inlined$parentFragmentViewModel$1.invoke(Unknown Source:2)
        at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:94)

    2020-02-12 10:54:43.083 25064-25064/fdsa.debug E/AndroidRuntime:     at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:83)
        at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:53)
        at com.airbnb.mvrx.lifecycleAwareLazy$1.onStart(lifecycleAwareLazy.kt:31)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        	... 34 more
     Caused by: java.lang.ClassCastException: androidx.navigation.fragment.NavHostFragment cannot be cast to fdsa.ParentFragment
        at fdsa.ParentFragment$Companion.create(ParentViewModel.kt:53)
        at fdsa.ParentFragment$Companion.create(ParentViewModel.kt:50)

**Comment by emitchel** [comment]
Confirmed not an issue on 1.3

**Comment by gpeal** [comment]
Fyi @elihart

**Comment by elihart** [comment]
Thanks for reporting, I will fix this in the alpha branch

**Comment by gpeal** [comment]
@emitchel This should be fixed in the latest alpha

**Comment by mahasadhu** [comment]
Hi @gpeal @elihart 

I'm facing the same error in Kitkat device
```
01-22 13:40:36.383 5436-5436/id.mahasadhu.githubtrending E/AndroidRuntime: FATAL EXCEPTION: main
    Process: id.mahasadhu.githubtrending, PID: 5436
    java.lang.RuntimeException: Unable to start activity ComponentInfo{id.mahasadhu.githubtrending/id.mahasadhu.githubtrending.presentation.MainActivity}: android.view.InflateException: Binary XML file line #45: Error inflating class androidx.fragment.app.FragmentContainerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #45: Error inflating class androidx.fragment.app.FragmentContainerView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at id.mahasadhu.githubtrending.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:55)
        at id.mahasadhu.githubtrending.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:49)
        at id.mahasadhu.githubtrending.presentation.MainActivity.onCreate(MainActivity.kt:20)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.airbnb.mvrx.MavericksFactoryKt.createViewModel(MavericksFactory.kt:46)
        at com.airbnb.mvrx.MavericksFactoryKt.access$createViewModel(MavericksFactory.kt:1)
        at com.airbnb.mvrx.MavericksFactory.create(MavericksFactory.kt:23)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at com.airbnb.mvrx.MavericksViewModelProvider.get(MavericksViewModelProvider.kt:65)
        at com.airbnb.mvrx.MavericksViewModelProvider.get$default(MavericksViewModelProvider.kt:39)
        at id.mahasadhu.githubtrending.presentation.home.HomeFragment$$special$$inlined$fragmentViewModel$1.invoke(MavericksExtensions.kt:44)
        at id.mahasadhu.githubtrending.presentation.home.HomeFragment$$special$$inlined$fragmentViewModel$1.invoke(MavericksExtensions.kt)
        at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:93)
        at com.airbnb.mvrx.DefaultViewModelDelegateFactory$createLazyViewModel$1.invoke(ViewModelDelegateProvider.kt:82)
        at com.airbnb.mvrx.lifecycleAwareLazy.getValue(lifecycleAwareLazy.kt:54)
        at com.airbnb.mvrx.lifecycleAwareLazy$1.onCreate(lifecycleAwareLazy.kt:32)
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2691)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
    	at androidx.fragment.app.FragmentManager.
```

**Comment by mahasadhu** [comment]
Wait, sometimes the same error appears on lollipop, I need to inspect this more

**Comment by mahasadhu** [comment]
I've made a new issue here https://github.com/airbnb/MvRx/issues/506
