### ISSUE TITLE
Impure reducer with state as Kotlin data class

### ISSUE THREAD

**Issue by eboudrant** [airbnb/MvRx#381]
I have a `MvRxState` which is a data class : 
```
data class MyState(
    val id: String?,
    val summary: Async<Summary> = Uninitialized,
    val installedTimeStamp: Long = 0L
) : MvRxState
```

And I got this ` Impure reducer` crash : 
```
Caused by: java.lang.IllegalArgumentException: Impure reducer set on MyViewModel! 
installedTimeStamp changed from 1588941641663 to 1588941641664. Ensure that your state 
properties properly implement hashCode.
 	at com.airbnb.mvrx.BaseMvRxViewModel$setState$1.invoke(BaseMvRxViewModel.kt:104)
 	at com.airbnb.mvrx.BaseMvRxViewModel$setState$1.invoke(BaseMvRxViewModel.kt:28)
 	at com.airbnb.mvrx.RealMvRxStateStore.flushSetStateQueue(RealMvRxStateStore.kt:190)
 	at com.airbnb.mvrx.RealMvRxStateStore.flushQueues(RealMvRxStateStore.kt:181)
 	at com.airbnb.mvrx.RealMvRxStateStore.access$flushQueues(RealMvRxStateStore.kt:18)
 	at com.airbnb.mvrx.RealMvRxStateStore$1.accept(RealMvRxStateStore.kt:52)
 	at com.airbnb.mvrx.RealMvRxStateStore$1.accept(RealMvRxStateStore.kt:18)
 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
```

I don't fully understand as my state is a Kotlin data class and have a correct `hashCode()`.

The crash is not reproductible easily. The `installedTimeStamp` value moved by 1ms and what is strange is this value is set only to one value in the view model lifecycle.

**Comment by gpeal** [comment]
@eboudrant Can you paste the reducer and your state class?
In debug mode, reducers are called twice in succession and MvRx ensures that your state is the same across both.

If you are calling something like `System.currentTimeMillis()` in a reducer, this will happen. To fix it, move the time outside of your reducer so you know you are setting the same one each time.

**Comment by eboudrant** [comment]
Ok, good to know, I had 
```
setState {
  copy(installedTimeStamp = System.currentTimeMillis())
}
```
So this should fix the problem :
```
val currentTimeMillis = System.currentTimeMillis()
setState {
  copy(installedTimeStamp = currentTimeMillis)
}
```

**Comment by gpeal** [comment]
Exactly!
