### ISSUE TITLE
The exception was not handled due to missing onError handler in the subscribe() method call

### ISSUE THREAD

**Issue by tomislavhofman** [airbnb/MvRx#393]
`com.airbnb.android:mvrx:1.3.0`

```
shrinkResources true
minifyEnabled true
```

```
f.c.i.b: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.AssertionError: impossible
        at f.c.k.d.b.a(EmptyCompletableObserver.java:3)
        at f.c.k.e.a.b$a.a(CompletableSubscribeOn.java:2)
        at f.c.k.e.a.a.b(CompletableFromCallable.java:8)
        at f.c.a.a(Completable.java:3)
        at f.c.k.e.a.b$a.run(CompletableSubscribeOn.java:1)
        at f.c.k.g.f.call(ScheduledDirectTask.java:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:269)
        at java.lang.Enum$1.create(Enum.java:260)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:286)
        at java.lang.Class.getEnumConstantsShared(Class.java:2291)
        at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40)
        at java.util.EnumSet.getUniverse(EnumSet.java:389)
        at java.util.EnumSet.noneOf(EnumSet.java:107)
        at java.util.EnumSet.of(EnumSet.java:321)
        at kotlin.reflect.jvm.internal.impl.builtins.g.<clinit>(PrimitiveType.java:10)
        at kotlin.reflect.jvm.internal.impl.builtins.g.m(PrimitiveType.java:1)
        at kotlin.reflect.jvm.internal.impl.builtins.f$e.<init>(KotlinBuiltIns.java:75)
        at kotlin.reflect.jvm.internal.impl.builtins.f.<clinit>(KotlinBuiltIns.java:8)
        at kotlin.reflect.jvm.internal.impl.builtins.m.b$b.<clinit>(FunctionClassDescriptor.kt:1)
        at kotlin.reflect.jvm.internal.impl.builtins.n.c.<clinit>(JavaToKotlinClassMap.kt:2)
        at kotlin.C.v.b.Q.b(RuntimeTypeMapper.kt:39)
        at kotlin.C.v.b.a.a(KClassImpl.kt:17)
        at kotlin.C.v.b.a$a$f.d(KClassImpl.kt:1)
        at kotlin.C.v.b.L.a(ReflectProperties.java:4)
        at kotlin.C.v.b.a$a.g(KClassImpl.kt:1)
        at kotlin.C.v.b.a.f(KClassImpl.kt:2)
        at kotlin.C.v.b.a.h(KClassImpl.kt:1)
        at kotlin.C.v.b.a$a$e.d(KClassImpl.kt:1)
        at kotlin.C.v.b.L.a(ReflectProperties.java:4)
        at kotlin.C.v.b.a$a.e(KClassImpl.kt:1)
        at kotlin.C.v.b.a.r(KClassImpl.kt:1)
        at kotlin.C.u.c.d(KClasses.kt:1)
        at com.airbnb.mvrx.a.a(BaseMvRxViewModel.kt:2)
        at com.airbnb.mvrx.a$a.call(java-style lambda group:4)
        at f.c.k.e.a.a.b(CompletableFromCallable.java:3)
        at f.c.a.a(Completable.java:3) 
        at f.c.k.e.a.b$a.run(CompletableSubscribeOn.java:1) 
        at f.c.k.g.f.call(ScheduledDirectTask.java:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:1981)
        at java.lang.Class.getDeclaredMethod(Class.java:1960)
        at java.lang.Enum$1.create(Enum.java:265)
        at java.lang.Enum$1.create(Enum.java:260) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
        at java.lang.Enum.getSharedConstants(Enum.java:286) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2291) 
        at java.lang.JavaLangAccess.getEnumConstantsShared(JavaLangAccess.java:40) 
        at java.util.EnumSet.getUniverse(EnumSet.java:389) 
        at java.util.EnumSet.noneOf(EnumSet.java:107) 
        at java.util.EnumSet.of(EnumSet.java:321) 
        at kotlin.reflect.jvm.internal.impl.builtins.g.<clinit>(PrimitiveType.java:10) 
        at kotlin.reflect.jvm.internal.impl.builtins.g.m(PrimitiveType.java:1) 
        at kotlin.reflect.jvm.internal.impl.builtins.f$e.<init>(KotlinBuiltIns.java:75) 
        at kotlin.reflect.jvm.internal.impl.builtins.f.<clinit>(KotlinBuiltIns.java:8) 
        at kotlin.reflect.jvm.internal.impl.builtins.m.b$b.<clinit>(FunctionClassDescriptor.kt:1) 
        at kotlin.reflect.jvm.internal.impl.builtins.n.c.<clinit>(JavaToKotlinClassMap.kt:2) 
        at kotlin.C.v.b.Q.b(RuntimeTypeMapper.kt:39) 
        at kotlin.C.v.b.a.a(KClassImpl.kt:17) 
        at kotlin.C.v.b.a$a$f.d(KClassImpl.kt:1) 
        at kotlin.C.v.b.L.a(ReflectProperties.java:4) 
        at kotlin.C.v.b.a$a.g(KClassImpl.kt:1) 
        at kotlin.C.v.b.a.f(KClassImpl.kt:2) 
        at kotlin.C.v.b.a.h(KClassImpl.kt:1) 
        at kotlin.C.v.b.a$a$e.d(KClassImpl.kt:1) 
        at kotlin.C.v.b.L.a(ReflectProperties.java:4) 
        at kotlin.C.v.b.a$a.e(KClassImpl.kt:1) 
        at kotlin.C.v.b.a.r(KClassImpl.kt:1) 
        at kotlin.C.u.c.d(KClasses.kt:1) 
        at com.airbnb.mvrx.a.a(BaseMvRxViewModel.kt:2) 
        at com.airbnb.mvrx.a$a.call(java-style lambda group:4) 
        at f.c.k.e.a.a.b(CompletableFromCallable.java:3) 
        at f.c.a.a(Completable.java:3) 
        at f.c.k.e.a.b$a.run(CompletableSubscribeOn.java:1) 
        at f.c.k.g.f.call(ScheduledDirectTask.java:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

With 
```
shrinkResources false
minifyEnabled false
```
it works just fine.

**Comment by tomislavhofman** [comment]
Fixed it by updating proguard as per :hearts:

**Comment by gpeal** [comment]
@tomislavhofman Try 1.4.0. It doesn't have kotlin-reflect anymore. If you are still getting it, please post a de-obfuscated stack.
