### ISSUE TITLE
Hilt support?

### ISSUE THREAD

**Issue by atonamy** [airbnb/MvRx#419]
New DI [Hilt](https://developer.android.com/training/dependency-injection/hilt-android) library from jetpack [support ViewModel](https://developer.android.com/training/dependency-injection/hilt-jetpack) but when I try to use it with MvRxViewModel it doesn't work and cause exception 

```
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment  calling Fragment constructor caused an exception
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:566)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
        at androidx.navigation.fragment.FragmentNavigator.instantiateFragment(FragmentNavigator.java:132)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:162)
        at androidx.navigation.fragment.FragmentNavigator.navigate(FragmentNavigator.java:58)
        at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.java:71)
        at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.java:28)
        at androidx.navigation.NavController.navigate(NavController.java:935)
        at androidx.navigation.NavController.onGraphCreated(NavController.java:577)
        at androidx.navigation.NavController.setGraph(NavController.java:534)
        at androidx.navigation.NavController.setGraph(NavController.java:499)
        at androidx.navigation.NavController.setGraph(NavController.java:481)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:237)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
```

Any workaround how to use Hilt with MvRx?

**Comment by sanogueralorenzo** [comment]
Same here,

Been testing out different approaches and the failure point relies on the ViewModel with the state due to the following:

Hilt required @InjectViewModel and @Assisted from the hilt library
MvRx requires @AssistedInject and @Assisted from the square library

In case anyone wants to give it a try: https://github.com/sanogueralorenzo/Android-Kotlin-Clean-Architecture/tree/c/mvrx_hilt

The project with dagger is the sample module and the viewmodel is `GifsViewModel`

**Comment by sanogueralorenzo** [comment]
I tried it out today and while you have to keep Assisted Inject it is possible.

See https://github.com/sanogueralorenzo/Android-Kotlin-Clean-Architecture/pull/116

**Comment by atonamy** [comment]
@sanogueralorenzo thanks
I also tried but I solved problem without AssistedInject just using `ExampleViewModel.Factory` as middleware object in Fragment to pass Hilt injection into MvRx ViewModel factory.

**Comment by sanogueralorenzo** [comment]
Could you share a code snippet of what you mean? Would like to check alternatives.

You also have an alternative here if you are using DaggerMvRxViewModelFactory https://github.com/airbnb/MvRx/pull/420

**Comment by atonamy** [comment]
In the example you gave you using

```
interface Factory  {
        fun create(state: SomeSate): SomeMvRxViewModel
}

```
And then you inject implementation for this interface in your `Fragment`, then in `MvRxViewModelFactory` you access this object from the fragment (where you inject `Factory`) and create `SomeMvRxViewModel`

Then if you do so you can inject everything you need inside `Factory` implementation without to use AssistedInject.

For example:

```
@FragmentScoped
class SomeMvRxViewModelFactoryImpl @Inject constructor(
    ...(some injected parameters here)
) : SomeMvRxViewModel.Factory {

    override fun create(state: SomeState): SomeMvRxViewModel {
        return SomeMvRxViewModel(state, ...(passed parameters))
    }
}
```

`Factory` interface can make generic so make code more reusable.

**Comment by rohandhruva** [comment]
With the new dagger 2.31 release, the `androidx.hilt` version of viewmodel injection is going to be deprecated. I created a new issue #502 to renew discussion.
