### ISSUE TITLE
failed to call observer method while running a couchbase contact app

### ISSUE THREAD

**Issue by namrahsheikh** [airbnb/MvRx#462]
Can anyone help me in resolving this error.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.molo17.couchbasedemo, PID: 3572
    java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ProcessLifecycleOwner.activityStarted(ProcessLifecycleOwner.java:111)
        at androidx.lifecycle.ProcessLifecycleOwner$2.onStart(ProcessLifecycleOwner.java:82)
        at androidx.lifecycle.ReportFragment.dispatchStart(ReportFragment.java:88)
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:108)
        at android.app.Fragment.performStart(Fragment.java:2548)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3008)
        at android.app.FragmentController.dispatchStart(FragmentController.java:193)
        at android.app.Activity.performStart(Activity.java:7264)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalArgumentException: Invalid scheme for URLEndpoint url (https). It must be either 'ws:' or 'wss:'.
        at com.couchbase.lite.URLEndpoint.<init>(URLEndpoint.java:59)
        at com.molo17.couchbasedemo.data.CouchbaseContactsRepository.startSync(CouchbaseContactsRepository.kt:73)
        at com.molo17.couchbasedemo.SyncLifecycleObserver.onStart(SyncLifecycleObserver.kt:15)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.lifecycle.ProcessLifecycleOwner.activityStarted(ProcessLifecycleOwner.java:111) 
        at androidx.lifecycle.ProcessLifecycleOwner$2.onStart(ProcessLifecycleOwner.java:82) 
        at androidx.lifecycle.ReportFragment.dispatchStart(ReportFragment.java:88) 
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:108) 
        at android.app.Fragment.performStart(Fragment.java:2548) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051) 
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3008) 
        at android.app.FragmentController.dispatchStart(FragmentController.java:193) 
        at android.app.Activity.performStart(Activity.java:7264) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by gpeal** [comment]
@namrahsheikh I don't think this is MvRx related. The call stack includes no MvRx code.

**Comment by namrahsheikh** [comment]
That application is now working for me.Could you please answer me how peer
to peer sync works in Couchbase.
If you have some idea on it.

Thanks and Regards
Namrah Sheikh

**Comment by gpeal** [comment]
@namrahsheikh I'm sorry, that is out of scope for MvRx. I'm going to have to close this issue.
Personally, I've also never used Couchbase so I can't help you there.
